"""Bring to current statE

Revision ID: 00889a472d5c
Revises: d335495a2c5c
Create Date: 2019-06-20 12:05:02.051205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00889a472d5c"
down_revision = "d335495a2c5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candidate", sa.Column("age_range_id", sa.Integer(), nullable=False))
    op.add_column("candidate", sa.Column("belief_id", sa.Integer(), nullable=True))
    op.add_column(
        "candidate", sa.Column("caring_responsibility", sa.Boolean(), nullable=True)
    )
    op.add_column("candidate", sa.Column("ethnicity_id", sa.Integer(), nullable=True))
    op.add_column("candidate", sa.Column("gender_id", sa.Integer(), nullable=True))
    op.add_column(
        "candidate",
        sa.Column("long_term_health_condition", sa.Boolean(), nullable=True),
    )
    op.add_column("candidate", sa.Column("sexuality_id", sa.Integer(), nullable=True))
    op.add_column(
        "candidate", sa.Column("working_pattern_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "candidate", "age_range", ["age_range_id"], ["id"])
    op.create_foreign_key(None, "candidate", "ethnicity", ["ethnicity_id"], ["id"])
    op.create_foreign_key(None, "candidate", "gender", ["gender_id"], ["id"])
    op.create_foreign_key(None, "candidate", "belief", ["belief_id"], ["id"])
    op.create_foreign_key(None, "candidate", "sexuality", ["sexuality_id"], ["id"])
    op.create_foreign_key(
        None, "candidate", "working_pattern", ["working_pattern_id"], ["id"]
    )
    op.drop_column("candidate", "type")
    op.drop_constraint("gender_candidate_id_fkey", "gender", type_="foreignkey")
    op.drop_column("gender", "candidate_id")
    op.drop_column("socio_economic", "free_school_meals")
    op.drop_column("socio_economic", "income_earner")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "socio_economic",
        sa.Column("income_earner", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "socio_economic",
        sa.Column(
            "free_school_meals", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "gender",
        sa.Column("candidate_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "gender_candidate_id_fkey", "gender", "candidate", ["candidate_id"], ["id"]
    )
    op.add_column(
        "candidate",
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "candidate", type_="foreignkey")
    op.drop_constraint(None, "candidate", type_="foreignkey")
    op.drop_constraint(None, "candidate", type_="foreignkey")
    op.drop_constraint(None, "candidate", type_="foreignkey")
    op.drop_constraint(None, "candidate", type_="foreignkey")
    op.drop_constraint(None, "candidate", type_="foreignkey")
    op.drop_column("candidate", "working_pattern_id")
    op.drop_column("candidate", "sexuality_id")
    op.drop_column("candidate", "long_term_health_condition")
    op.drop_column("candidate", "gender_id")
    op.drop_column("candidate", "ethnicity_id")
    op.drop_column("candidate", "caring_responsibility")
    op.drop_column("candidate", "belief_id")
    op.drop_column("candidate", "age_range_id")
    # ### end Alembic commands ###
