"""Add withdrawn flag to Application model, default False

Revision ID: 079240fd2753
Revises: 00889a472d5c
Create Date: 2019-06-21 07:27:42.847220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "079240fd2753"
down_revision = "00889a472d5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application", sa.Column("withdrawn", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "withdrawn")
    # ### end Alembic commands ###
