"""Drop personal_email column now it is safe to do so

Revision ID: 0bcdc20a2c99
Revises: 2115ecb81393
Create Date: 2019-06-07 18:30:35.515565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcdc20a2c99'
down_revision = '2115ecb81393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candidate_personal_email_key', 'candidate', type_='unique')
    op.drop_column('candidate', 'personal_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('personal_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('candidate_personal_email_key', 'candidate', ['personal_email'])
    op.execute(
        "UPDATE candidate SET personal_email = email_address"
    )
    # ### end Alembic commands ###
