"""Update Application table with protected characteristics and remove Fast Stream flag

Revision ID: 1bf521badcf7
Revises: 9bf0d694b5ac
Create Date: 2019-05-21 12:45:11.898471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bf521badcf7"
down_revision = "9bf0d694b5ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("changeable_protected_characteristics", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "application",
        "changeable_protected_characteristics",
        ["changeable_protected_characteristics"],
        ["id"],
    )
    op.drop_column("application", "fast_stream")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("fast_stream", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "application_changeable_protected_characteristics_fkey",
        "application",
        type_="foreignkey",
    )
    op.drop_column("application", "changeable_protected_characteristics")
    # ### end Alembic commands ###
