"""Change personal_email to email_address

Revision ID: 2115ecb81393
Revises: 5995ecd39f79
Create Date: 2019-06-07 17:38:33.912700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2115ecb81393"
down_revision = "5995ecd39f79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate", sa.Column("email_address", sa.String(length=120), nullable=True)
    )
    op.create_unique_constraint(None, "candidate", ["email_address"])
    op.execute("UPDATE candidate SET email_address = personal_email;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("candidate_email_address_key", "candidate", type_="unique")
    op.drop_column("candidate", "email_address")
    # ### end Alembic commands ###
