"""Remove DOB field

Revision ID: 266a2516befd
Revises: ca1d1ff9204d
Create Date: 2019-05-21 12:01:36.198021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266a2516befd'
down_revision = 'ca1d1ff9204d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_date_of_birth', table_name='candidate')
    op.drop_column('candidate', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_candidate_date_of_birth', 'candidate', ['date_of_birth'], unique=False)
    # ### end Alembic commands ###
