"""role table

Revision ID: 2c4072a98a1f
Revises: f65406c034f5
Create Date: 2019-05-02 15:47:43.595957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4072a98a1f'
down_revision = 'f65406c034f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation', sa.Integer(), nullable=True),
    sa.Column('date_started', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['organisation'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
