"""Changeable protected characteristics fk on Candidate model should end in _id

Revision ID: 32f494d61331
Revises: 221ca84895ae
Create Date: 2019-06-20 09:36:36.681281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f494d61331'
down_revision = '221ca84895ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('changeable_protected_characteristics_id', sa.Integer(), nullable=True))
    op.drop_constraint('candidate_changeable_protected_characteristics_fkey', 'candidate', type_='foreignkey')
    op.create_foreign_key(None, 'candidate', 'changeable_protected_characteristics', ['changeable_protected_characteristics_id'], ['id'])
    op.drop_column('candidate', 'changeable_protected_characteristics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('changeable_protected_characteristics', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.create_foreign_key('candidate_changeable_protected_characteristics_fkey', 'candidate', 'changeable_protected_characteristics', ['changeable_protected_characteristics'], ['id'])
    op.drop_column('candidate', 'changeable_protected_characteristics_id')
    # ### end Alembic commands ###
