"""Add Intake table

Revision ID: 36b8172da4c4
Revises: 64b269b8d0bc
Create Date: 2019-07-04 15:05:50.205458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36b8172da4c4"
down_revision = "64b269b8d0bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intake",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scheme_start_date", sa.Date(), nullable=True),
        sa.Column("scheme_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["scheme_id"], ["scheme.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intake_scheme_start_date"),
        "intake",
        ["scheme_start_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intake_scheme_start_date"), table_name="intake")
    op.drop_table("intake")
    # ### end Alembic commands ###
