"""empty message

Revision ID: 3e58649d0bee
Revises: f8cf9a92aca3
Create Date: 2019-05-02 15:17:58.645947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e58649d0bee'
down_revision = 'f8cf9a92aca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_email', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('scheme', sa.String(length=10), nullable=True),
    sa.Column('scheme_start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_email')
    )
    op.create_index(op.f('ix_candidate_date_of_birth'), 'candidate', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_candidate_scheme_start_date'), 'candidate', ['scheme_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_scheme_start_date'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_date_of_birth'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###
