"""Change default temporary promotion to 'None'

Revision ID: 4545f69ecd58
Revises: e192be3bded0
Create Date: 2019-06-17 12:00:21.835969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4545f69ecd58'
down_revision = 'e192be3bded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'temporary_promotion', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'temporary_promotion', server_default=False)
    # ### end Alembic commands ###
