"""Link Role and Promotion

Revision ID: 496431eda64c
Revises: c3c47033fefa
Create Date: 2019-07-09 14:37:13.940190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496431eda64c'
down_revision = 'c3c47033fefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_change_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'promotion', ['role_change_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'role_change_id')
    # ### end Alembic commands ###
