"""Drop application_id from candidate

Revision ID: 5844729f6859
Revises: 5f7addaabfa5
Create Date: 2019-06-20 10:39:45.332179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5844729f6859'
down_revision = '5f7addaabfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candidate_application_id_fkey', 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'application_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('candidate_application_id_fkey', 'candidate', 'application', ['application_id'], ['id'])
    # ### end Alembic commands ###
