"""Add first name, last name

Revision ID: 5995ecd39f79
Revises: 50446c3e2c93
Create Date: 2019-06-07 14:45:59.124148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5995ecd39f79"
down_revision = "50446c3e2c93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate", sa.Column("first_name", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "candidate", sa.Column("last_name", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate", "last_name")
    op.drop_column("candidate", "first_name")
    # ### end Alembic commands ###
