"""Remove unneeded Intake table

Revision ID: 5f7f164653d3
Revises: 36b8172da4c4
Create Date: 2019-07-05 10:55:48.921142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f7f164653d3"
down_revision = "36b8172da4c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_intake_scheme_start_date", table_name="intake")
    op.drop_table("intake")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intake",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("scheme_start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("scheme_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["scheme_id"], ["scheme.id"], name="intake_scheme_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="intake_pkey"),
    )
    op.create_index(
        "ix_intake_scheme_start_date", "intake", ["scheme_start_date"], unique=False
    )
    # ### end Alembic commands ###
