"""Add AuditEvent table

Revision ID: 64b269b8d0bc
Revises: e2e908ecf10a
Create Date: 2019-07-04 11:11:13.562440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64b269b8d0bc"
down_revision = "e2e908ecf10a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_taken", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_event")
    # ### end Alembic commands ###
