"""Link Application and Leadership

Revision ID: 668033b0c2b4
Revises: 
Create Date: 2019-05-09 15:13:49.859828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668033b0c2b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leadership', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leadership', 'application', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leadership', type_='foreignkey')
    op.drop_column('leadership', 'application_id')
    # ### end Alembic commands ###
