"""Remove unique constraint on Organisation parent id

Revision ID: 70d2ad268ad7
Revises: 668033b0c2b4
Create Date: 2019-05-10 09:12:14.987670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70d2ad268ad7"
down_revision = "668033b0c2b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organisation", sa.Column("parent_organisation_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "organisation_organisation_id_fkey", "organisation", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "organisation", "organisation", ["parent_organisation_id"], ["id"]
    )
    op.drop_column("organisation", "organisation_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organisation",
        sa.Column("organisation_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "organisation_parent_organisation_id_fkey", "organisation", type_="foreignkey"
    )
    op.create_foreign_key(
        "organisation_organisation_id_fkey",
        "organisation",
        "organisation",
        ["organisation_id"],
        ["id"],
    )
    op.drop_column("organisation", "parent_organisation_id")
    # ### end Alembic commands ###
