"""Convert joining_grade to joining_gtade_id

Revision ID: 8bd57cbf8d7a
Revises: bfdf3ca8520e
Create Date: 2019-07-26 15:54:14.933420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd57cbf8d7a'
down_revision = 'bfdf3ca8520e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('joining_grade_id', sa.Integer(), nullable=True))
    op.drop_constraint('candidate_joining_grade_fkey', 'candidate', type_='foreignkey')
    op.create_foreign_key(None, 'candidate', 'grade', ['joining_grade_id'], ['id'])
    op.drop_column('candidate', 'joining_grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('joining_grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.create_foreign_key('candidate_joining_grade_fkey', 'candidate', 'grade', ['joining_grade'], ['id'])
    op.drop_column('candidate', 'joining_grade_id')
    # ### end Alembic commands ###
