"""Add rank column

Need to be able to order grades by seniority. This seems the only way

Revision ID: 995695afd23e
Revises: ac055b2632f1
Create Date: 2019-05-23 14:28:37.285170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "995695afd23e"
down_revision = "ac055b2632f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grade", sa.Column("rank", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grade", "rank")
    # ### end Alembic commands ###
