"""Add Changeable ProtectedCharacteristics table

Revision ID: 9bf0d694b5ac
Revises: 4a9dd737b772
Create Date: 2019-05-21 12:42:07.706134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf0d694b5ac'
down_revision = '4a9dd737b772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changeable_protected_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belief', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=256), nullable=True),
    sa.Column('sexuality', sa.String(length=128), nullable=True),
    sa.Column('caring_responsibility', sa.Boolean(), nullable=True),
    sa.Column('long_term_health_condition', sa.Boolean(), nullable=True),
    sa.Column('age_range_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('working_pattern_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('belief')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belief',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='belief_pkey')
                    )
    op.drop_table('changeable_protected_characteristics')
    # ### end Alembic commands ###
