"""Link Candidate to Application

Revision ID: 9e38a3e36f7e
Revises: 70d2ad268ad7
Create Date: 2019-05-10 09:27:53.392370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e38a3e36f7e'
down_revision = '70d2ad268ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'application', 'candidate', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_candidate_id_fkey', 'application', type_='foreignkey')
    op.drop_column('application', 'candidate_id')
    # ### end Alembic commands ###
