"""Add location_tag to Location table

Revision ID: a090dd5c7f79
Revises: f1348313cba5
Create Date: 2019-06-06 11:22:42.033915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a090dd5c7f79"
down_revision = "f1348313cba5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location", sa.Column("location_tag", sa.String(length=16), nullable=True)
    )
    op.create_index(
        op.f("ix_location_location_tag"), "location", ["location_tag"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_location_tag"), table_name="location")
    op.drop_column("location", "location_tag")
    # ### end Alembic commands ###
