"""Link SocioEconomicBackground to incomeEarnerEmployeStatus

Revision ID: ac055b2632f1
Revises: f0e142a1b233
Create Date: 2019-05-22 14:48:04.711467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac055b2632f1'
down_revision = 'f0e142a1b233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socio_economic', sa.Column('income_earner_employee_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'socio_economic', 'income_earner_employee_status', ['income_earner_employee_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('socio_economic_income_earner_employee_status_id_fkey', 'socio_economic', type_='foreignkey')
    op.drop_column('socio_economic', 'income_earner_employee_status_id')
    # ### end Alembic commands ###
