"""Add Grade to Role

Revision ID: bf7f2303b52b
Revises: 682f5a1b937c
Create Date: 2019-05-10 09:35:18.464077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7f2303b52b'
down_revision = '682f5a1b937c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'grade', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'grade_id')
    # ### end Alembic commands ###
