"""Add promotions table

Revision ID: c3c47033fefa
Revises: 5f7f164653d3
Create Date: 2019-07-09 14:27:07.280753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3c47033fefa"
down_revision = "5f7f164653d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=28), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promotion_value"), "promotion", ["value"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promotion_value"), table_name="promotion")
    op.drop_table("promotion")
    # ### end Alembic commands ###
