"""Link SocioEconomic to Candidate

Revision ID: c46df9260505
Revises: d218e8ce6a0d
Create Date: 2019-05-13 07:50:00.826465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46df9260505'
down_revision = 'd218e8ce6a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socio_economic', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'socio_economic', 'candidate', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'socio_economic', type_='foreignkey')
    op.drop_column('socio_economic', 'candidate_id')
    # ### end Alembic commands ###
