"""Add 'successful' flag to Application

Revision ID: ca1d1ff9204d
Revises: c46df9260505
Create Date: 2019-05-13 07:55:55.568227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1d1ff9204d'
down_revision = 'c46df9260505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('successful', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'successful')
    # ### end Alembic commands ###
