"""Remove ProtectedCharacteristics table

Revision ID: d335495a2c5c
Revises: 5844729f6859
Create Date: 2019-06-20 11:01:58.003248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd335495a2c5c'
down_revision = '5f7addaabfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changeable_protected_characteristics')
    op.add_column('gender', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gender', 'candidate', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gender', type_='foreignkey')
    op.drop_column('gender', 'candidate_id')
    op.create_table('changeable_protected_characteristics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caring_responsibility', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('long_term_health_condition', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('age_range_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('working_pattern_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('belief_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sexuality_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ethnicity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['age_range_id'], ['age_range.id'], name='changeable_protected_characteristics_age_range_id_fkey'),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name='changeable_protected_characteristics_application_id_fkey'),
    sa.ForeignKeyConstraint(['belief_id'], ['belief.id'], name='changeable_protected_characteristics_belief_id_fkey'),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['ethnicity.id'], name='changeable_protected_characteristics_ethnicity_id_fkey'),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], name='changeable_protected_characteristics_gender_id_fkey'),
    sa.ForeignKeyConstraint(['sexuality_id'], ['sexuality.id'], name='changeable_protected_characteristics_sexuality_id_fkey'),
    sa.ForeignKeyConstraint(['working_pattern_id'], ['working_pattern.id'], name='changeable_protected_characteristics_working_pattern_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='changeable_protected_characteristics_pkey')
    )
    # ### end Alembic commands ###
