"""Add LSEB flag to MainJobType

Revision ID: dbd912ab36e8
Revises: f61d93b55701
Create Date: 2019-07-04 09:23:10.645187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbd912ab36e8"
down_revision = "f61d93b55701"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "main_job_type",
        sa.Column("lower_socio_economic_background", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("main_job_type", "lower_socio_economic_background")
    # ### end Alembic commands ###
