"""Must have rank

Revision ID: eadbcbde0556
Revises: 995695afd23e
Create Date: 2019-05-23 14:33:14.747455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadbcbde0556'
down_revision = '995695afd23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grade', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grade', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
