"""Correct missing 'id' on aspirational grade

Revision ID: eb885b326420
Revises: 079240fd2753
Create Date: 2019-07-01 12:48:10.738474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb885b326420'
down_revision = '079240fd2753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('aspirational_grade_id', sa.Integer(), nullable=True))
    op.drop_constraint('application_aspirational_grade_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'grade', ['aspirational_grade_id'], ['id'])
    op.drop_column('application', 'aspirational_grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('aspirational_grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_aspirational_grade_fkey', 'application', 'grade', ['aspirational_grade'], ['id'])
    op.drop_column('application', 'aspirational_grade_id')
    # ### end Alembic commands ###
