"""Remove extraneous field

Revision ID: f0e142a1b233
Revises: f6ca2a5cba30
Create Date: 2019-05-21 16:27:10.048855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0e142a1b233"
down_revision = "ff5e1c887861"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("socio_economic", "people_employed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "socio_economic",
        sa.Column(
            "people_employed", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
