"""Add ethnicity table and link to Candidate

Revision ID: f1348313cba5
Revises: 34851186e7a6
Create Date: 2019-06-06 11:15:30.666291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1348313cba5'
down_revision = '34851186e7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ethnicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.Column('bame', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidate', sa.Column('ethnicity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'ethnicity', ['ethnicity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'ethnicity_id')
    op.drop_table('ethnicity')
    # ### end Alembic commands ###
