"""Application must have Candidate

Revision ID: f195b7cb6a18
Revises: 9e38a3e36f7e
Create Date: 2019-05-10 09:28:26.213031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f195b7cb6a18'
down_revision = '9e38a3e36f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
