"""Fix role table

Revision ID: f390f6f0c8b1
Revises: 2c4072a98a1f
Create Date: 2019-05-02 16:09:26.607565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f390f6f0c8b1'
down_revision = '2c4072a98a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.drop_constraint('role_organisation_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'organisation', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'role', 'candidate', ['candidate_id'], ['id'])
    op.drop_column('role', 'organisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('organisation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_organisation_fkey', 'role', 'candidate', ['organisation'], ['id'])
    op.drop_column('role', 'organisation_id')
    op.drop_column('role', 'candidate_id')
    # ### end Alembic commands ###
