"""Change personal_email to email_address

Revision ID: f3904e94e2ed
Revises: 5995ecd39f79
Create Date: 2019-06-07 14:50:36.217189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3904e94e2ed'
down_revision = '5995ecd39f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='candidate', column_name='personal_email', new_column_name='email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='candidate', column_name='email_address', new_column_name='personal_email')
    # ### end Alembic commands ###
