"""Make self-identification field longer in SociocoEconomic

Revision ID: f6ca2a5cba30
Revises: ff5e1c887861
Create Date: 2019-05-21 16:26:33.877826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ca2a5cba30'
down_revision = 'ff5e1c887861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socio_economic', sa.Column('self_identify_lower_socio_economic_background', sa.String(length=256), nullable=True))
    op.drop_column('socio_economic', 'self_identify_lower_socio_economic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socio_economic', sa.Column('self_identify_lower_socio_economic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('socio_economic', 'self_identify_lower_socio_economic_background')
    # ### end Alembic commands ###
