"""Add belief to ChangeableProtectedCharacteristics

Revision ID: fbcfff699099
Revises: 1bf521badcf7
Create Date: 2019-05-21 15:15:55.888338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcfff699099'
down_revision = '1bf521badcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('changeable_protected_characteristics', sa.Column('belief_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'changeable_protected_characteristics', 'belief', ['belief_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'changeable_protected_characteristics', type_='foreignkey')
    op.drop_column('changeable_protected_characteristics', 'belief_id')
    op.drop_table('belief')
    # ### end Alembic commands ###
