"""Add FreeSchoolMeals table and link to Socioeconomic

Revision ID: ff5e1c887861
Revises: 30a1ee0f4c3c
Create Date: 2019-05-21 16:21:09.431252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5e1c887861'
down_revision = '30a1ee0f4c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_school_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('socio_economic', sa.Column('free_school_meals_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'socio_economic', 'free_school_meals', ['free_school_meals_id'], ['id'])
    op.drop_column('socio_economic', 'eligible_free_school_meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socio_economic', sa.Column('eligible_free_school_meals', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('socio_economic_free_school_meals_id_fkey', 'socio_economic', type_='foreignkey')
    op.drop_column('socio_economic', 'free_school_meals_id')
    op.drop_table('free_school_meals')
    # ### end Alembic commands ###
